### PR TITLE
lowercase hostnames

### PR DESCRIPTION
**Pull request by sydneyli**
fixes EFForg/starttls-everywhere#59

### CODE REVIEW

**Comment by mfb** [comment]
👍 Looks good to me. Although this repo could use some CI :)

**Comment by mfb** [comment]
It looks like to fully resolve this, you also need to run ToLower() on the cert names, because it's doing a case-sensitive string comparison when validating? Unless the tls library is converting to lower case for you?

**Comment by sydneyli** [comment]
good call @mfb! more `ToLower`s in the cert validation check.

**Comment by mfb** [comment]
👍

**Pull request merged**
